name: phpcbf

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr, phpcbf

      - name: Run phpcbf
        run: phpcbf src
      - name: Git commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git add docs/classes
          git commit -m "Update phpdoc" || echo "No changes to commit"
          git push