# This workflow helps developer cleanup and then check there code
name: cleanup and check

on:
  push

jobs:
  php-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: "7.4"
          php_extensions: redis exif
          version: 2.x
          command: require symfony/test-pack
      - name: Run tests
        run: php vendor/phpunit/phpunit/phpunit --coverage-text
  dependency-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: "7.4"
          php_extensions: redis exif
          version: 2.x
      - name: composer audit
        run: composer audit
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: "7.4"
          php_extensions: redis exif
          version: 2.x
          command: require clean/phpdoc-md
      - name: Build the docs
        run: vendor/bin/phpdoc-md
      - name: Git commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git pull
          git add docs/classes
          git commit -m "Update phpdoc" || echo "No changes to commit"
          git push
  php-cbf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr, phpcbf

      - name: Run phpcbf
        run: phpcbf .
        continue-on-error: true
      - name: Git commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git pull
          git add src
          git commit -m "Update src from PHP Codesniffer" || echo "No changes to commit"
          git push
  remark-lint:
    name: runner / remark-lint
    runs-on: ubuntu-latest
    needs: documentation
    steps:
      - uses: actions/checkout@v2
      - name: install remark presets
        run: npm install remark-cli remark-preset-lint-consistent remark-preset-lint-recommended remark-lint-list-item-indent
        shell: bash
      - name: run remark
        run: npx remark . --output --use remark-preset-lint-consistent --use remark-preset-lint-recommended --use remark-lint-list-item-indent
      - name: Git commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git pull
          git add .
          git reset package.json
          git reset package-lock.json
          git reset node_modules
          git commit -m "Update src from remark-lint" || echo "No changes to commit"
          git push
  php-cf:
    runs-on: ubuntu-latest
    needs: php-cbf
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr, phpcs
      - name: Run phpcs
        run: phpcs -q --report=checkstyle . | cs2pr
  php-md:
    runs-on: ubuntu-latest
    needs: php-cbf
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: cs2pr, phpmd
      - name: Run phpmd
        run: phpmd src github phpmd.xml --not-strict
