# .github/workflows/version.yml
name: Git Version

on:
  push:
    branches:
      - master
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      #Based on https://github.com/marketplace/actions/git-version
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main

      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}
      - name: Update composer.json version
      - name: Update config.json
        run: echo "`jq '.version="${{ steps.version.outputs.version }}"' composer.json`" > composer.json
      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.previous-version }}